// <auto-generated />
using System;
using EfCoreHasDataNestedOwnedTypes.SimpleNullable;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreHasDataNestedOwnedTypes.Migrations.SimpleNullable
{
    [DbContext(typeof(SimpleNullableDbContext))]
    partial class SimpleNullableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreHasDataNestedOwnedTypes.SimpleNullable.RootEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NullableString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RootEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96e1d442-bdd0-4c6f-9d01-624b27abbac3"),
                            NullableString = "Hi"
                        },
                        new
                        {
                            Id = new Guid("aae51dac-016e-472e-ad51-2f09f8cb9fbb")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
