// <auto-generated />
using System;
using EfCoreHasDataNestedOwnedTypes.NullableObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreHasDataNestedOwnedTypes.Migrations.NullableObject
{
    [DbContext(typeof(NullableObjectDbContext))]
    [Migration("20211123093856_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreHasDataNestedOwnedTypes.NullableObject.RootEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RootEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96e1d442-bdd0-4c6f-9d01-624b27abbac3")
                        },
                        new
                        {
                            Id = new Guid("aae51dac-016e-472e-ad51-2f09f8cb9fbb")
                        });
                });

            modelBuilder.Entity("EfCoreHasDataNestedOwnedTypes.NullableObject.RootEntity", b =>
                {
                    b.OwnsOne("EfCoreHasDataNestedOwnedTypes.NullableObject.OwnedEntityLevel1", "OwnedEntityLevel1", b1 =>
                        {
                            b1.Property<Guid>("RootEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RootEntityId");

                            b1.ToTable("RootEntities");

                            b1.WithOwner()
                                .HasForeignKey("RootEntityId");

                            b1.HasData(
                                new
                                {
                                    RootEntityId = new Guid("96e1d442-bdd0-4c6f-9d01-624b27abbac3"),
                                    Id = new Guid("8f8eea73-0b43-412a-b0aa-a9338db6e067")
                                });
                        });

                    b.Navigation("OwnedEntityLevel1");
                });
#pragma warning restore 612, 618
        }
    }
}
