// <auto-generated />
using System;
using EfCoreHasDataNestedOwnedTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreHasDataNestedOwnedTypes.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20211118072635_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreHasDataNestedOwnedTypes.EntityLevel1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EntityLevel1s");
                });

            modelBuilder.Entity("EfCoreHasDataNestedOwnedTypes.EntityLevel1", b =>
                {
                    b.OwnsOne("EfCoreHasDataNestedOwnedTypes.OwnedEntity1", "OwnedEntity1", b1 =>
                        {
                            b1.Property<Guid>("EntityLevel1Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("MyProperty")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EntityLevel1Id");

                            b1.ToTable("EntityLevel1s");

                            b1.WithOwner()
                                .HasForeignKey("EntityLevel1Id");
                        });

                    b.Navigation("OwnedEntity1");
                });
#pragma warning restore 612, 618
        }
    }
}
